# Competition configuration options
options:
  insert_models_over_bins: true

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    destinations: [any]
    products:
      part_0:
        type: piston_rod_part
        pose:
          xyz: [0.1, 0.1, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin4:
    models:
      piston_rod_part:
        xyz_start: [0.1, 0.15, 0.0]
        xyz_end: [0.35, 0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 3
        num_models_y: 3


time_limit: -1
