sensors:
  logical_camera_bin4:
    type: logical_camera
    pose:
      xyz: [-0.3, 0.383, 1.27]
      rpy: [0.2, 1.5707, 0]
  logical_camera_agv1:
    type: logical_camera
    pose:
      xyz: [0.3, 3.15, 1.29]
      rpy: [0, 'pi/2', 0]
  logical_camera_agv2:
    type: logical_camera
    pose:
      xyz: [0.3, -3.15, 1.29]
      rpy: [0, 'pi/2', 0]

